### ISSUE TITLE
Finish phase0 spec

### ISSUE THREAD

**Issue by ralexstokes** [ralexstokes/ethereum_consensus#29]
Great progress has been made on the phase0 spec!

Here is a list of what is left:

- [x] process_epoch
  - [x]  process_justification_and_finalization https://github.com/ralexstokes/ethereum_consensus/pull/56
  - [x] process_rewards_and_penalties https://github.com/ralexstokes/ethereum_consensus/pull/46
  - [x] process_registry_updates: https://github.com/ralexstokes/ethereum_consensus/pull/42
  - [x] process_slashings: https://github.com/ralexstokes/ethereum_consensus/pull/39
  - [x] process_eth1_data_reset: https://github.com/ralexstokes/ethereum_consensus/pull/31
  - [x] process_effective_balance_updates https://github.com/ralexstokes/ethereum_consensus/pull/47
  - [x] process_slashings_reset: https://github.com/ralexstokes/ethereum_consensus/pull/32
  - [x] process_randao_mixes_reset:  https://github.com/ralexstokes/ethereum_consensus/pull/33
  - [x] process_historical_roots_update: https://github.com/ralexstokes/ethereum_consensus/pull/37
  - [x] process_participation_record_updates: https://github.com/ralexstokes/ethereum_consensus/pull/36
- [x] process_block
  - [x] process_block_header: https://github.com/ralexstokes/ethereum_consensus/pull/34
  - [x] process_randao: https://github.com/ralexstokes/ethereum_consensus/pull/40
  - [x] process_eth1_data: https://github.com/ralexstokes/ethereum_consensus/pull/41
  - [x] process_operations
    - [x] process_proposer_slashing: https://github.com/ralexstokes/ethereum_consensus/pull/45
    - [x] process_attester_slashing: https://github.com/ralexstokes/ethereum_consensus/pull/48
    - [x] process_attestation: https://github.com/ralexstokes/ethereum_consensus/pull/49
    - [x] process_deposit: https://github.com/ralexstokes/ethereum_consensus/pull/50
    - [x] process_voluntary_exit: https://github.com/ralexstokes/ethereum_consensus/pull/51

Each of these remaining bits are fairly self-contained and should be highly parallelizable.

**Comment by ralexstokes** [comment]
just added skeletons for all the various sub-transitions in 68a652bbfc269ff142c7b36e97c78b6d7ae68eaa and e63b7e12050085d3e03c5b2157f610d435d200ce

**Comment by buchhlz2** [comment]
@ralexstokes starting with `process_eth1_data_reset` since it seems rather straightforward...opening a PR now. Let me know if my process, description, nomenclature, etc. is on-par with what you've been doing in the repo.

**Comment by buchhlz2** [comment]
`process_slashings_reset`: https://github.com/ralexstokes/ethereum_consensus/pull/32

Lmk if you want me to continue commenting here with each fn's PR and fn I'm finishing for visibility purposes...or if I should just make the PR and leave this thread alone, etc.

**Comment by buchhlz2** [comment]
`process_randao_mixes_reset`: https://github.com/ralexstokes/ethereum_consensus/pull/33

**Comment by ralexstokes** [comment]
> Lmk if you want me to continue commenting here with each PR & fn I'm finishing, for visibility purposes...or if I should just make the PR and leave this thread alone, etc.

either way is fine! don't feel like you need to if you don't want to

**Comment by ralexstokes** [comment]
and with https://github.com/ralexstokes/ethereum_consensus/commit/7ee866705840e21a9842c0136884a00903516ea7 the phase 0 spec should be implemented.

next will be testing and then optimizations :)
