### ISSUE TITLE
Implement the phase0 spec

### ISSUE THREAD

**Issue by ralexstokes** [ralexstokes/ethereum_consensus#9]
I think enough of the skeleton is in place to start churning out consensus code!

I'd suggest starting with a fairly faithful representation of the code here:

https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#block-processing

in Rust.

We will want to optimize various parts but it is best to start with the "naive" un-optimized version as I'd also like this repo to be as "understandable" as possible to someone who is interfacing w/ the consensus protocol for the first time via this library.

I'd suggest starting w/ the `apply_block` function here https://github.com/ralexstokes/ethereum_consensus/blob/main/src/phase0/state_transition.rs#L4

and filling in the rest!

**Comment by dnkolegov** [comment]
What is `apply_block`? There is no such function in the spec.

**Comment by ralexstokes** [comment]
Update: started this w/ #12 and made great progress thanks to @dnkolegov!

I think the only thing outstanding wrt to handling the compile-time constants to add some `Context` data to cut down on the verbosity of the const generics -- there are functions that use the constants and it seems `rustc` cannot infer usage within the function body and requires us to explicit wire the constants through. 

Instead, I'm leaning towards making preset-specific `Context`s that will just have some of these constants in them.

**Comment by ralexstokes** [comment]
Closing in lieu of #29.
